# Initially snatched and adapted from libsodium .travis.yml

sudo: false

language: cpp

cache: ccache

os:
 - linux

addons:
  apt:
    packages:
    - libcxxtools-dev

before_script:
 - ( cd tntdb && ./autogen.sh )

script:
 - ( cd tntdb && ./configure --disable-dependency-tracking )
 - ( cd tntdb && make distcheck )
 - ( cd tntdb && make distclean > /dev/null )
 - ( cd tntdb && ./configure --disable-dependency-tracking --enable-minimal )
 - ( cd tntdb && make distcheck )
